<?php

namespace AppBundle\Repository\Blog;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function drop() {
        $query = $this->_em->createQuery('DELETE AppBundle:Blog\User p');
        $query->execute();
    }
}
